spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
    show-sql: true

jwt:
  secret: ${JWT_SECRET}

app:
  notify:
    url: ${SENDMAILSERVICE_URL}


security:
  public-paths:
    - ${REGISTRATION_PATH:/api/v1/registration}
    - ${CONFIRM_PATH:/api/v1/registration/confirm}
    - ${LOGIN_PATH:/login}